
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name:thiagomusique
  version: '0.1' 
  summary: A little shell for testing 
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.

  grade: devel 
  confinement: devmode 

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
